app:
    name: toirtis-dev
    debug: true

logging:
    level: DEBUG
    file:
        path: logs/toirtis_dev.log
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    console:
        format: "%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        colors:
            DEBUG: cyan
            INFO: green
            WARNING: yellow
            ERROR: red
            CRITICAL: red,bg_white

db:
    filename: toirtis_dev.db
    connection_string: sqlite+aiosqlite:///toirtis_dev.db
    overwrite: false

tasks:
    - name: metrics_collection
      class: MetricsTask
      frequency: 10
      enabled: true

    - name: mock_camera_capture
      class: MockCameraTask # Using mock camera for development
      frequency: 15
      enabled: true
      parameters:
          cameras:
              - port: 0 # MacBook built-in camera (if using OpenCV)
                name: mock_cam0
                output_folder: dev_images/cam0
              - port: 1 # Mock second camera
                name: mock_cam1
                output_folder: dev_images/cam1
          image_format: jpg
          quality: 85
          resolution:
              width: 1280
              height: 720
          rotation: 0
          capture_timeout: 5
          retry_attempts: 2


    - name : robot_task
      class: RobotTask
      frequency: 5
      enabled: true
      parameters:
          front_servo_port: /dev/ttyAM0
          back_servo_port: /dev/ttyAM1
          front_servo_ids : [2, 6, 3, 5]
          back_servo_ids : [4, 6, 1, 2]

    - name : can_monitor
      class: CanTask
      frequency: 5
      enabled: true
      parameters:
        spi_bus : 1
        cs_pin : 0
        loopback : false
        silent : false
        listen_timeout : 1
