app:
    name: toirtis-dev
    debug: true

logging:
    level: DEBUG
    file:
        path: logs/toirtis_dev.log
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    console:
        format: "%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        colors:
            DEBUG: cyan
            INFO: green
            WARNING: yellow
            ERROR: red
            CRITICAL: red,bg_white

db:
    filename: toirtis_dev.db
    connection_string: sqlite+aiosqlite:///toirtis_dev.db
    overwrite: false

tasks:
    - name: metrics_collection
      class: MetricsTask
      frequency: 10
      enabled: true

    - name : can_monitor
      class: CanTask
      frequency: 5
      enabled: true
      parameters:
        spi_bus : 1
        cs_pin : D5
        loopback : false
        silent : false
        listen_timeout : 1
