app:
    name: toirtis-dev
    debug: true

logging:
    level: DEBUG
    file:
        path: logs/toirtis_dev.log
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    console:
        format: "%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        colors:
            DEBUG: cyan
            INFO: green
            WARNING: yellow
            ERROR: red
            CRITICAL: red,bg_white

db:
    filename: toirtis_dev.db
    connection_string: sqlite+aiosqlite:///toirtis_dev.db
    overwrite: false

tasks:
    - name: metrics_collection
      class: MetricsTask
      frequency: 10
      enabled: true

    - name: camera_capture
      class: CameraTask
      frequency: 2
      enabled: true
      parameters:
          cameras:
              - port: 0
                name: cam0
                output_folder: images/cam0
          image_format: jpg
          quality: 95
          resolution:
              width: 1920
              height: 1080
          rotation: 180
          capture_timeout: 3
          retry_attempts: 1

    - name : robot_task
      class: RobotTask
      frequency: 5
      enabled: true
      parameters:
          front_servo_port: /dev/ttyACM0
          back_servo_port: /dev/ttyACM1
          front_servo_ids : [2, 6, 3, 5]
          back_servo_ids : [4, 6, 1, 2]

    - name : mock_can_monitor
      class: MockCanTask
      frequency: 5
      enabled: true
      parameters:
        spi_bus : 1
        cs_pin : 0
        loopback : false
        silent : false
        listen_timeout : 1
        mock_strategy : landing_sequence
